name: CI-Test

on:
  push:
    branches:
      - '**' # Trigger on all branches

permissions:
  contents: read # As assets are not uploaded

env:
  NODE_OPTIONS: --max-old-space-size=7168

jobs:
  test:
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - name: Install missing dependencies on Linux
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install libudev-dev libusb-1.0-0-dev

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run unit tests
        run: yarn test

  trunk-check:
    name: Trunk Check
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - name: Install missing dependencies on Linux
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install libudev-dev libusb-1.0-0-dev

      - name: Install dependencies
        run: yarn install --immutable

      - name: Install Trunk CLI
        run: |
          curl https://get.trunk.io -fsSL | bash
          echo "$HOME/.trunk/bin" >> $GITHUB_PATH

      - name: Run Trunk via yarn check:trunk
        run: yarn check:trunk

  build:
    name: Production build
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - name: Install missing dependencies on Linux
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install libudev-dev libusb-1.0-0-dev

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run build
        run: yarn build
